- name: Task level variables 
  hosts: local 
  connection: local 
  vars: 
   Course: "AWS with DevOps"  
   Duration: "100HR" 
   Trainer: "sivakumar"
  tasks: 
   - name: Print course info 
     vars: 
       Course: "Ansible"
       Duration: "10HR" 
       Trainer: "Sivakumar" 
     ansible.builtin.debug: 
       msg: "Course is {{ Course}}, Duration is {{ Duration }}, Trainer is {{ Trainer }}"

   - name: print course info 
     ansible.builtin.debug: 
      msg: "Course is {{ Course}}, Duration is {{ Duration }}, Trainer is {{ Trainer }}"       