- name: Variable from vars-files
  hosts: local 
  connection: local 
  vars_file: 
    - course.yaml
  tasks: 
   - name: course info 
     ansible.builtin.debug: 
      msg:"Hello, This course is {{ Course }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
       