- name: functions 
  hosts: local 
  connection: local 
  vars: 
    persons: "jyothi,keerthi,sneha,suvarsha"
  tasks:
   - name: check undefine variables 
     ansible.builtin.debug: 
      msg: "hello, {{ person | default('jyothi') }}" 

   - name: check undefine variables 
     ansible.builtin.debug: 
      msg: "hello, {{ person | split(',') }}"    
    